### ISSUE TITLE
[Outfitter ERROR] Download failed for workshop 3110399912: file

### ISSUE THREAD

**Issue by Wilczeecho** [Metastruct/outfitter#93]
[Outfitter ERROR] Download failed for workshop 3110399912: file

**Comment by jule14** [comment]
Try updating your game again, an update to gmod introduced a bug that should be fixed now.

**Comment by Birdypotato** [comment]
> Try updating your game again, an update to gmod introduced a bug that should be fixed now.

I have the same issue and had just updated it, its still broken

**Comment by SoundCrafterYT** [comment]
I have exact same issue after the gmod update

**Comment by bewflast** [comment]
same

**Comment by bewflast** [comment]
example
```
[Outfitter] doRefresh	nil
[Outfitter] Bodygroup	BTN	Refresh
[Outfitter] Bodygroup	BTN	Refresh
[Outfitter] Bodygroup	BTN	Refresh
[Outfitter] FetchWS	3110399912
[Outfitter] steamworks.FileInfo	3110399912	->	table: 0x9fac9e72
[Outfitter] 	title	Mr. Bean (San Andreas Mod) Playermodel & NPCs
[Outfitter] 	owner	76561198046176844
[Outfitter] 	tags	Addon,Model,Cartoon,Fun
[Outfitter] 	size	757.85 KB
[Outfitter] 	fileid	0
[Outfitter] 	created ago	6 days
[Outfitter] Preload AlreadyMounted	3110399912	content/4000/3110399912/temp.gma	File	757.85 KB	ret=	true	false	lua/autorun/mrbeangta.lua
[Outfitter] DownloadUGC	3110399912		result	content/4000/3110399912/temp.gma	File
[Outfitter] DownloadUGC	3110399912	returning	content/4000/3110399912/temp.gma	File	
[Outfitter] Download	3110399912	to	content/4000/3110399912/temp.gma	took	0.25038970000014
[Outfitter] FetchWS downloading 3110399912 failed for reason: file
[❤] FetchWS downloading 3110399912 failed for reason: file
[Outfitter] UIChoseWorkshop	3110399912	FetchWS failed:	file	nil
[Outfitter] doRefresh	nil
[Outfitter] Bodygroup	BTN	Refresh
[Outfitter] Bodygroup	BTN	Refresh
[Outfitter] Bodygroup	BTN	Refresh
[❤] Download failed for workshop 3110399912: file
[Outfitter ERROR] Download failed for workshop 3110399912: file
```

`x86-64 - Chromium + 64-bit binaries` branch

**Comment by Python1320** [comment]
Should be fixed now
